export enum SOCKET_LOGIN_LISTEN {
    IS_USERNAME_EXIST = 'IS_USERNAME_EXIST',
    GET_IP_ADDRESS = 'GET_IP_ADDRESS',
    USER_ADD = 'USER_ADD',
    FORCE_LOGOUT = 'FORCE_LOGOUT',
    IS_NOREF_EXIST = 'IS_NOREF_EXIST',
    LOGIN_NOTIF = 'LOGIN_NOTIF',
    NOTIF_PESAN = 'NOTIF_PESAN',
}